-- Use an admin role
USE ROLE ACCOUNTADMIN;

-- Create the `reporter` role
CREATE ROLE IF NOT EXISTS REPORTER;

-- Create the `preset` user and assign to role
CREATE USER IF NOT EXISTS PRESET
  PASSWORD='presetPassword123'
  LOGIN_NAME='preset'
  MUST_CHANGE_PASSWORD=FALSE
  DEFAULT_WAREHOUSE='COMPUTE_WH'
  DEFAULT_ROLE='REPORTER'
  DEFAULT_NAMESPACE='AIRBNB.DEV'
  COMMENT='Preset user used for creating reports';

-- Assign role `reporter` to users
GRANT ROLE REPORTER TO USER PRESET;
GRANT ROLE REPORTER TO ROLE TRANSFORM;
GRANT ROLE REPORTER TO ROLE ACCOUNTADMIN;

-- Create our database and schemas
CREATE DATABASE IF NOT EXISTS AIRBNB;
CREATE SCHEMA IF NOT EXISTS AIRBNB.RAW;

-- Set up permissions to role `reporter`
GRANT ALL ON WAREHOUSE COMPUTE_WH TO ROLE REPORTER;
GRANT USAGE ON DATABASE AIRBNB TO ROLE REPORTER;
GRANT USAGE ON SCHEMA AIRBNB.DEV TO ROLE REPORTER;